Auth/issue-2-auth-implementation
adnan23062000/readers_hub pull request #4
Opened 2023-03-13 14:53 UTC by adnan23062000

Register and login feature done

2023-03-15 15:19 UTC, edge555 commented on controller/user.controller.js
> +            if(results===null || results===undefined)
not a proper way

2023-03-15 15:20 UTC, edge555 commented on controller/user.controller.js
>              algorithm: "HS256",
keep the algorithm name in env file

2023-03-15 15:21 UTC, edge555 commented on controller/user.controller.js
> +            success: 1,
avoid 0/1, use true/false

2023-03-15 15:22 UTC, edge555 commented on utils/user.utils.js
> +        const salt = bcrypt.genSaltSync(10);
keep salting rounds in env file

2023-03-16 13:01 UTC, rafaelragib requested changes

2023-03-16 13:01 UTC, rafaelragib commented on service/auth.service.js
> +        const username = await convertToLowerCase(data.username);
why this function is asynchronous?

2023-03-16 13:01 UTC, rafaelragib commented on service/auth.service.js
> +        return await UserService.createUser(username, data.email, data.password);
try to use one parameter by passing one object

2023-03-16 13:01 UTC, rafaelragib commented on service/user.service.js
> +    getUserWithPassword: async (userName) => {
use one function to get user by username as discussed

2023-03-16 13:01 UTC, rafaelragib commented on service/user.service.js
> +        if(user===null || user===undefined)
```suggestion
        if(!user)
```

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +        console.log(user, password);
remove console.log

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +const jwt = require('jsonwebtoken');
unused library here

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +            return res.status(401).json({
why response return is used?

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +        const username = req.body.username;
this will fail in runtime if body is undefined

2023-03-16 13:01 UTC, rafaelragib commented on DTO/blog.dto.js
remove the blog works from this branch if possible

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +        const username = req.body.username;
runtime error if body is undefined

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +        const user = await authService.userLogin(username);
no validation for undefined username

2023-03-16 13:01 UTC, rafaelragib commented on controller/auth.controller.js
> +        if (!username || !password || !passwordMatched) {
if a username or password is not given in the request. why will the response be an incorrect username or password?

2023-03-16 13:01 UTC, rafaelragib commented on controller/user.controller.js
> +const jwt = require('jsonwebtoken');
unused library in this file

2023-03-16 13:01 UTC, rafaelragib commented on controller/user.controller.js
> +            const results = await getUserByUsername(convertToLowerCase(userName));
```suggestion
            const result = await getUserByUsername(convertToLowerCase(userName));
```
the method indicates that it will return only one user but the variable name is plural

2023-03-21 04:16 UTC, rafaelragib approved these changes

2023-03-21 06:25 UTC, merged